server {
    listen 80;

    # Identifies the official domain names the server will respond to.
    server_name hcioffi.dev www.hcioffi.dev;
    client_max_body_size 6M;
    
    # HC: Serves the React Frontend (Production Build)
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # HC: Proxies API requests to the .NET Backend
    location /api {
        proxy_pass http://meu_site_api:8080;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    # HC: Proxies static file requests (uploads) to the .NET Backend
    # This ensures images saved in wwwroot/uploads are reachable
    location /uploads {
        proxy_pass http://meu_site_api:8080;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}