server {
    listen 80;
    
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Proxy for API calls (Optional, depends on how you handle CORS)
    # error_page 500 502 503 504 /50x.html;
}